// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chat": {
            "get": {
                "description": "Get all chats",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get all chats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Chat"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new chat",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Create a new chat",
                "parameters": [
                    {
                        "description": "chat",
                        "name": "chat",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Chat"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/core.Chat"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/memory/chat/{chat_id}/fetch": {
            "post": {
                "description": "Fetch memories for a given chat.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memories"
                ],
                "summary": "Fetch Memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fetch Memories Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.MemoryFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.ScoredMemory"
                            }
                        }
                    }
                }
            }
        },
        "/memory/long-term/chat/{chat_id}": {
            "get": {
                "description": "Get long term memories for a given chat.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memories"
                ],
                "summary": "Get Long Term Memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.LongTermMemory"
                            }
                        }
                    }
                }
            }
        },
        "/memory/short-term/chat/{chat_id}": {
            "get": {
                "description": "Get short term memories for a given chat.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "memories"
                ],
                "summary": "Get Short Term Memories",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat ID",
                        "name": "chat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.ShortTermMemory"
                            }
                        }
                    }
                }
            }
        },
        "/message": {
            "post": {
                "description": "Sends a message to classification queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Add message",
                "parameters": [
                    {
                        "description": "Message",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.NewMessage"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/v1.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "core.Chat": {
            "type": "object",
            "properties": {
                "external_id": {
                    "type": "string"
                }
            }
        },
        "core.LongTermMemory": {
            "type": "object",
            "properties": {
                "access_count": {
                    "type": "integer"
                },
                "active": {
                    "type": "boolean"
                },
                "chat_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                }
            }
        },
        "core.MemoryFetchRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Max number of memories to be returned (Default: 2)",
                    "type": "integer",
                    "example": 2
                },
                "long_term_threshold": {
                    "description": "Specific threshold for long term memories (Default: 0.8)",
                    "type": "number",
                    "example": 0.8
                },
                "text": {
                    "description": "Text to be searched",
                    "type": "string",
                    "example": "I love smart LLMs"
                },
                "vector_search_limit": {
                    "description": "Max number of memories to be returned from vector search (Default: 10)",
                    "type": "integer",
                    "example": 10
                },
                "vector_search_threshold": {
                    "description": "Min score to considerate a memory (Default: 0.6)",
                    "type": "number",
                    "example": 0.6
                }
            }
        },
        "core.MemoryTypeEnum": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "NoMemory",
                "ShortTerm",
                "LongTerm"
            ]
        },
        "core.NewMessage": {
            "type": "object",
            "properties": {
                "chat_id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "core.NewShortTermMemory": {
            "type": "object",
            "properties": {
                "access_count": {
                    "type": "integer"
                },
                "active": {
                    "type": "boolean"
                },
                "chat_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "memory": {
                    "type": "string"
                },
                "merge_count": {
                    "type": "integer"
                },
                "merged": {
                    "type": "boolean"
                }
            }
        },
        "core.ScoredMemory": {
            "type": "object",
            "properties": {
                "memoryType": {
                    "$ref": "#/definitions/core.MemoryTypeEnum"
                },
                "score": {
                    "type": "number"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "core.ShortTermMemory": {
            "type": "object",
            "properties": {
                "embedded": {
                    "$ref": "#/definitions/core.NewShortTermMemory"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "v1.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
